server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  location /auth/login {
    proxy_pass http://api-gateway:8081;
    proxy_set_header Host $host;
  }

  location /auth/register {
    proxy_pass http://auth-service:8082;
    proxy_set_header Host $host;
  }

  location /catalog {
    proxy_pass http://api-gateway:8081;
    proxy_set_header Host $host;
  }

  location /orders {
    proxy_pass http://order-service:8084;
    proxy_set_header Host $host;
  }
}
